### ISSUE TITLE
Deactivate Interpolator

### ISSUE THREAD

**Issue by behinger** [MakieOrg/TopoPlots.jl#10]
I think we should allow
`interpolation = False`

This would allow to plot things like:
![grafik](https://user-images.githubusercontent.com/10183650/178259507-130ab5ed-c538-4043-81ee-5cdbf37aa8ab.png)
and 
![grafik](https://user-images.githubusercontent.com/10183650/178259840-786f1f9d-ba91-403e-91b0-74f5fc1c6b63.png)

Should be straight forward to add another `if interpolation == False` catch where we select for Delauny/Splines Interpolations, right?

**Comment by palday** [comment]
The electrode placements are rotated 90 degrees in your image (also visible as swapped x and y on the axis).

It might be easier to define a "null interpolator" that returns zero everywhere except the electrode locations, but you still need allow accepting an electrode "size" as a parameter to get your second image.

**Comment by behinger** [comment]
images are from google

electrode locations hve afaik already marker color set to value, ergo I'd remove it.

Not sure if you can modify electrode size already, but I think so

**Comment by behinger** [comment]
@palday your idea works well - I made two pulls, one for the markersize and one for the nullinterpolator.
