### ISSUE TITLE
Call scipy directly via PythonCall

### ISSUE THREAD

**Issue by SimonDanisch** [MakieOrg/TopoPlots.jl#11]
Reading https://discourse.julialang.org/t/ann-pythoncall-and-juliacall/76778/24 and seeing the much better python package installation integration, it seems worth quite a bit to switch to PythonCall directly to call our one python dependency...

**Comment by ericphanson** [comment]
FYI I just ran into an issue with Julia 1.7 on ubuntu and the brand new scipy 1.9 this week, so I would bound to scipy 1.8 if you run into difficulties. Ref also https://github.com/cjdoris/CondaPkg.jl/issues/43

**Comment by behinger** [comment]
how exactly did you solve this? I have the same issue with PyMNE

**Comment by ericphanson** [comment]
I upper bounded scipy to 1.8

**Comment by palday** [comment]
@behinger I've been trying to track down a segfaulting issue on clean installs in PyMNE from something that changed in the Python dependency stack in the last week. I don't think it's just scipy, but scipy definitely is playing a role.
