### ISSUE TITLE
EEG TopoPlot colorrange issue with data type

### ISSUE THREAD

**Issue by geigermartin** [MakieOrg/TopoPlots.jl#23]
Hi, I noticed a small problem when setting the 'colorrange' attribute for the eeg_topoplot() function. The colors inside the circles that indicate channel locations are unaffected by the new colorrange if the data is passed as Vector{Any} instead of Vector{Float32}.

![colorrange](https://user-images.githubusercontent.com/104988690/203344934-ae6fad38-3b7c-45ca-9698-aa7d2fa62436.png)

**Comment by palday** [comment]
Can you post an MWE? You can use `TopoPlots.example_data()` for example data.

**Comment by behinger** [comment]
seems to resolved itselve - I tried this:
```julia

let
    data, positions = TopoPlots.example_data()
    d = Array{Any}(undef,10)
    d[1:10] .= 1:10
    f, ax, pl = topoplot(d,positions[1:10];colorrange=[-1,5],label_scatter=true,markersize=10)
end
```
