### ISSUE TITLE
Data description is missing

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/TopoPlots.jl#40]
Nowhere in the documentation is there a description of the data dimensions for this code:
`data, positions = TopoPlots.example_data()`.
It has three dimensions: 64×400×3. But what do they represent? 
Specifying this will greatly improve the usability of the package, especially for new users.

**Comment by behinger** [comment]
agreed, should be added to the docstring.

64 => channels
400 => timepoints @ 500Hz, from -0.3 to 0.5
3 => three different estimates, first is a mean effect over subjects, second is standard deviation over subjects, third is a p-value (within t-test)

Origin is Ehinger 2015
