### ISSUE TITLE
multiple layout arrangements

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/TopoPlots.jl#41]
Currently, if I do `data, positions = TopoPlots.example_data()` I have only opportunity to get 64 channel position.
But if I want 32, or 128 channels layout? Would be nice to have such arrangements too.

**Comment by behinger** [comment]
I'm not sure this is the right package to host something like this. Why do you want/expect this data from this package?

to be more helpful: 32 you could subsample the dataset

**Comment by vladdez** [comment]
- I can subsample 32, but will they be evenly distributed?
- I can not do that with 128

I expected that from the package which I use to simulate the data for topoplots. Would be nice to have smth like `TopoPlots.example_data(layout = 128)`.

**Comment by behinger** [comment]
I recommend using UnfoldSim.jl to simulate your own data, which easily can reach 250 channels. 

The example_data in TopoPlots cannot account for all possible use cases
