### ISSUE TITLE
label_text=true doesn't work

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/TopoPlots.jl#48]
As you can see in [documentation example ](https://makieorg.github.io/TopoPlots.jl/stable/eeg/) it is impossible to show label text for electrodes. 
Seems like a bug.

**Comment by palday** [comment]
I suspect this is due to [other issues in the recipe system on Makie 0.20](https://github.com/MakieOrg/Makie.jl/issues/3514), but we should probably create a workaround here.

**Comment by behinger** [comment]
this is the same as #39  - I'm going for a small rewrite of the eeg_topoplot recipe anyway, I'll fix it.
