### ISSUE TITLE
Variety of `CHANNELS_10_20`

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/TopoPlots.jl#51]
Why `TopoPlots.CHANNELS_10_20` currently has only option for 19 electrodes? Why not to allow an option for 32, 64 and 128 electrodes?

**Comment by palday** [comment]
There is no reason not to include them besides nobody having done it. Simon and I only had use for those 19 channels, which are the most common in clinical research, where higher density setups are rare. Pull requests are most welcome. 😊
