### ISSUE TITLE
NaturalNeighboursMethod fail

### ISSUE THREAD

**Issue by behinger** [MakieOrg/TopoPlots.jl#55]
Hi @asinghvi17 - the NaturalNeighboursMethod seems to fail, already e.g. in the general.md docs example I get a
```julia
ERROR: TaskFailedException

    nested task error: KeyError: key (10, 9, 8) not found
```
Any idea whats going on?

**Comment by behinger** [comment]
@asinghvi17 any points on this, else I will take out that example for now. I dont have time to debug that code

**Comment by DanielVandH** [comment]
@behinger If you still want to fix it, you can send me the example code that led to that error I can debug it. Usually it's the same cause everytime but a bit hard to explain
