### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/TopoPlots.jl#59]
I suppose the package lacks "Cite this repository" section or button.

**Comment by behinger** [comment]
@palday @asinghvi17 @SimonDanisch should we do a Zenodo release/doi? JOSS paper is probably too much hassle?

**Comment by palday** [comment]
I think Zenodo is the way to go, but we'll need a MakieOrg admin to enable the Zenodo integration

**Comment by behinger** [comment]
should be available with next release :)
