### ISSUE TITLE
Is there a way to manipulate font of channel labels?

### ISSUE THREAD

**Issue by vladdez** [MakieOrg/TopoPlots.jl#65]
Currently on some images channel labels merge into background. Wound be nice to be able to change their color, size, boldness etc.

**Comment by palday** [comment]
You can use Makie [Themes](https://docs.makie.org/dev/explanations/theming/themes) and specify various [fonts](https://docs.makie.org/dev/explanations/fonts).

```julia
using CairoMakie, TopoPlots

data, positions = TopoPlots.example_data()

labels = ["s$i" for i in 1:size(data, 1)]

with_theme(Theme(; fontsize=25, fonts=(; regular="Courier New"))) do
       TopoPlots.eeg_topoplot(data[:, 340, 1]; labels, label_text=true, positions, axis=(aspect=DataAspect(),))
end
```

![Image](https://github.com/user-attachments/assets/c9a721c2-b34d-4bfe-b453-ecee96e3ff32)

**Comment by vladdez** [comment]
Great feature! Thank you very much! I guess putting this into documentation would be quite helpful.
